title: "Hardware Insights"
description: "A blog about computer hardware, reviews, and insights."
baseurl: "" 
url: "https://sopheadave.github.io" 
theme: minima
markdown: kramdown

# Enable plugins
plugins:
  - jekyll-feed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
