title: "Hardware Insights"
email: "your-email@example.com"
description: "A blog about computer hardware, reviews, and insights."
baseurl: "" 
url: "https://sopheadave.github.io" 
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
